services:
  postgres:
    image: postgres:10
    environment:
      POSTGRES_DB: demodb
      POSTGRES_USER: admin # Sensitive value, should be stored in .env or github secretes
      POSTGRES_PASSWORD: strongpw # Sensitive value, should be stored in .env or github secretes
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  spring-boot-app:
    build:
      context: ./spring-boot-app
      dockerfile: Dockerfile
    environment:
      APP_NODE_URL: http://node-app:8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demodb
      SPRING_DATASOURCE_USERNAME: admin # Sensitive value, should be stored in .env or github secretes
      SPRING_DATASOURCE_PASSWORD: strongpw # Sensitive value, should be stored in .env or github secretes
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  node-app:
    build:
      context: ./node-app
      dockerfile: Dockerfile
    environment:
      API_URL: http://spring-boot-app:8080
    ports:
      - "8081:8081"
    depends_on:
      - spring-boot-app

volumes:
  postgres-data: